# Generated by Django 4.2.10 on 2024-03-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_delete_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
