# Generated by Django 4.2.10 on 2024-03-28 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_likes'),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='blog.post'),
        ),
    ]
